### ISSUE TITLE
Mylyn connectors install page only offers old/broken versions

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-mylyn/org.eclipse.mylyn#169]
Opening the mylyn connector discovery UI by doing:

1. Show Task Repositories view
2. Press Add Task Repository button ![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/679236/3ac77c33-b60d-4fb3-aba2-f422787a5235)
3. Press Install More Connectors

This is the UI I am presented with:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/679236/d61018c1-cb87-4b6e-94e9-0421f2c092f9)

Every entry in this list is either not installable (Foglyn is disabled, see #166 for probable reason, others fail to install due to version mismatches), installs but is completely non-functional (Mantis installs, but then a lot of Guava errors are encountered after restart), or installs an older version (all Eclipse provided ones are old version 3.25.2.v20200814-0512).

In the error log I can see it accessing the 3.25 snapshot of Mylyn to fill this discovery window, I guess that the URLs in https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/adbfdf433caeccd3e808cad3aabb37c52d447411/org.eclipse.mylyn.discovery-directory/plugin.xml#L80 need updating?

**Comment by mjmeijer** [comment]
When this discovery feature was introduced there were wild dreams of a marketplace for connectors that would provide a business model for Tasktop Inc. That never materialized and maintaining this up to date list for the connectors proved to be a maintenance burden with little effect. Meanwhile most connectors are also listed in the Eclipse Marketplace and maintained there by their owners.

So a radical proposal for removing this maintenance burden from the Mylyn team:
- try and make Mylyn connectors a category in the Eclipse Marketplace
- create API for questioning a specific category in the Marketplace plugin
- simplify the mylyn discovery plugin to query the Eclipse Marketplace directly rather than duplicating the maintenance effort.
@wimjongman what do you think?

**Comment by wimjongman** [comment]
Even more radical: I think we should drop the connector discovery logic altogether.

**Comment by jonahgraham** [comment]
+1 for removal of the functionality.

**Comment by gnl42** [comment]
+1 for ditching it.

We should also take a look at cleaning up/remove/re-create https://wiki.eclipse.org/Mylyn/Extensions

**Comment by ruspl-afed** [comment]
+1 for remove in 3.27, for upcoming 3.26.1 let's consider anesthetic #176

**Comment by jonahgraham** [comment]
The update in #176 is better as it removes all the errors, broken plug-ins, etc. But it does leave this confusing error message that reads "Connector discovery completed without finding any connectors. Please check your Internet connection and try again."

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/679236/e2500dba-2ee9-488c-9003-e6cd9c1dce6e)

I am really just providing this update as a known issue to help others potentially find it since the plan to fully ditch this functionality soon means it probably isn't worth doing anything else.

**Comment by BeckerFrank** [comment]
I close this, here the result from the latest nightly build.
![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/13169360/691a9ff7-b4d7-4a3a-b865-041161bc5dbb)
