### ISSUE TITLE
Eclipse Dash action should not cause build failure

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn#202]
Actually I don't like this decision. 
But I do not see good alternative at the moment, because in case of any false positive the PR is blocked (see #201 for example).

So, let's configure Eclipse Dash action to not fail

**Comment by merks** [comment]
You can change it back when the backlog is clear.

**Comment by ruspl-afed** [comment]
@HannesWell is it possible to configure license check to not fail using[ standard action](https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/3bfff8a8fcd1e51f77f353bcce76f89c6f9b59f5/.github/workflows/licensecheck.yml#L19)? 
What I found looks like ["always fail"](https://github.com/eclipse/dash-licenses/blob/fedc9183fcb67c2f723159d29e6db2216952ce7b/.github/actions/maven-license-check-action/action.yml#L31) 
Perhaps, I'm looking to the wrong place.

**Comment by HannesWell** [comment]
> @HannesWell is it possible to configure license check to not fail using[ standard action](https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/3bfff8a8fcd1e51f77f353bcce76f89c6f9b59f5/.github/workflows/licensecheck.yml#L19)? 

It is right that currently the workflow always fails if the license-vetting could not succeed.
I can look into adding a configuration option to not fail the build if the license check has failed, next week, but it might not be straight forward because I have to check if this might break assumption for downstream code.
But I then would be concerned about being not aware of license-check failures, because I assume that nobody really checks the workflow logs if interaction is required.
Not vetted licenses in-between releases are not a problem AFAIK, but when you perform a release all dependencies should be vetted and a failure in the license-check is IMHO a good heads up.

In general you are free to ignore the failing license-check workflow, when you want to merge a PR. That was actually the main reason why I created a separate workflow independent of the regular build+text workflow, so that one can see immediately that there is only a license-vetting issue, but technically the change is fine because the build+test workflow succeeds.
If one does the license-check in the same workflow as building and testing it would indeed be annoying because one would never know if there are technical issues occur later in the pipeline, hidden by the license-check failure. But due to the separate failure you can distinguish pressingly. 

It looks like you could exclude a failing license check from blocking the merge:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

Personally I think that this is a good compromise. It does not fail your build+tests, but you are still aware of the situation.
But of course if you insist I can build in an option to not fail the workflow if license vetting fails.

**Comment by ruspl-afed** [comment]
Well, somehow we live with it, there's nothing else to do here at the moment.
