### ISSUE TITLE
Merge Mylyn Docs git Repository into Mylyn git Repository

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#315]
Instead of working on #313 the plan is now first to move the whole Mylyn Docs Repository into the Mylyn Repository.

Here the planed steps.

- [x] migrate the Repository and make sure that we have a working Workspace setup and a combined Jenkins Build with all combined stages
- [ ] setup Mylyn Docs only GitHub Actions in Mylyn
- [x] rework the maven definition so that we have one maven build
- [x] rework the Jenkins files so that we can perform all previous possible steps from one Jenkinsfile
- [x] rework the p2 Update Sites
- [ ] rework the html Website and GitHub pages to point to the new stuff

**Comment by akurtakov** [comment]
Should mylyn.docs git repo be archived now? At least smth should be done to note that it should no longer be used.

**Comment by merks** [comment]
I just remembered that the mylyn docs is using the old feature image:

https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/main/mylyn.docs/wikitext/core/org.eclipse.mylyn.wikitext/feature.gif

rather than the new one:

https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/main/mylyn.builds/org.eclipse.mylyn.builds.core/mylyn.png

It will of course be good to make that consistently the new one...

**Comment by merks** [comment]
It seems a little scary late to do it now...

**Comment by ruspl-afed** [comment]
Do you plan to update Mylyn Docs contribution for SimRel 2023-12 @akurtakov ?

**Comment by akurtakov** [comment]
@merks do we need such a release for dependencies sake? If not I don't plan to.

**Comment by merks** [comment]
The existing contribution does not result in any duplicates, so I see no compelling reason to create work for yourself.

**Comment by ruspl-afed** [comment]
@BeckerFrank it seems that your effort to merge Mylyn Docs into Mylyn was not brought to the attention of all the participants well enough, since we still have changes in Mylyn Docs repository. Please announce you plan more widely (perhaps, you can create a dedicated discussion item) and please ensure that we don't have to support two copies of Mylyn Docs.
Since final Mylyn 4.1 drop for SimRel 2023-12 is expected today, it may be ideal timeframe to merge Mylyn and Mylyn Docs into one project.
cc: @merks

**Comment by ruspl-afed** [comment]
Mylyn Release contribution was done

**Comment by ruspl-afed** [comment]
>  setup Mylyn Docs only GitHub Actions in Mylyn

I don't think that we need this point @BeckerFrank

**Comment by BeckerFrank** [comment]
> > setup Mylyn Docs only GitHub Actions in Mylyn
> 
> I don't think that we need this point @BeckerFrank

I was thinking that we need to change the https://github.com/eclipse-mylyn page as there is a link to the now archived https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs for new issues.

We may also no longer need the .github page for "global issues and discussions" as we now only have one repository

**Comment by ruspl-afed** [comment]
Good point. Please take care about this when you have time.

**Comment by olberger** [comment]
Instructions for filing issues need to be addressed too. See https://github.com/eclipse-mylyn/.github/issues/36 
Hth,

**Comment by ruspl-afed** [comment]
@BeckerFrank in fact this is done, please extract not yet complete items to a dedicated tickets, if they are still actual.
